# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e7e1e3"

# Title color for boxes
theme[title]="#d2c2d2"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#cfc3cd"

# Background color of selected item in processes box
theme[selected_bg]="#d2c2d2"

# Foreground color of selected item in processes box
theme[selected_fg]="#372d39"

# Color of inactive/disabled text
theme[inactive_fg]="#cac5c7"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d5c0d7"

# Cpu box outline color
theme[cpu_box]="#949091"

# Memory/disks box outline color
theme[mem_box]="#949091"

# Net up/down box outline color
theme[net_box]="#949091"

# Processes box outline color
theme[proc_box]="#949091"

# Box divider line and small boxes line color
theme[div_line]="#494647"

# Temperature graph colors
theme[temp_start]="#cfc3cd"
theme[temp_mid]="#d2c2d2"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#cfc3cd"
theme[cpu_mid]="#d2c2d2"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#cfc3cd"
theme[free_mid]=""
theme[free_end]="#4c444d"

# Mem/Disk cached meter
theme[cached_start]="#d5c0d7"
theme[cached_mid]=""
theme[cached_end]="#514254"

# Mem/Disk available meter
theme[available_start]="#d2c2d2"
theme[available_mid]=""
theme[available_end]="#4e4350"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#cfc3cd"
theme[download_mid]="#d2c2d2"
theme[download_end]="#d5c0d7"

# Upload graph colors
theme[upload_start]="#cfc3cd"
theme[upload_mid]="#d2c2d2"
theme[upload_end]="#d5c0d7"
