-- Generated by nwg-displays on 2026-05-20 at 12:25:43. Do not edit manually.

hl.monitor({
	output = "eDP-1",
	mode = "1366x768@60.0",
	position = "0x672",
	scale = 1.0,
	cm = "hdr",
	sdrbrightness = 1.2,
	sdrsaturation = 0.98,
})
hl.monitor({
	output = "HDMI-A-1",
	mode = "2560x1440@59.95",
	position = "1366x0",
	scale = 1.0,
	bitdepth = 10,
	cm = "hdr",
	sdrbrightness = 1.2,
	sdrsaturation = 0.98,
	vrr = 1,
})
