[Audio]
Volume=125

[General]
ColorScheme=Material You Dark (darker titlebar2)
FileDialogLastLocation=file:///home/nitin/Downloads/ABDM/Videos
FloatingFooterTrigger=BottomMouseMovement
FooterStyle=floating
GuiStyle=Darkly
LastPlayedFile=file:///home/nitin/Downloads/ABDM/Videos/IN.THE.GREY.2026.2160p.AMZN.WEB-DL.DDP5.1.Atmos.H.265-SCOPE.mkv
LastUrl=https://87d6a6ef6b58-webstreamrmbg.baby-beamup.club/%7B%22multi%22%3A%22on%22%2C%22en%22%3A%22on%22%7D/extract/?index=0&url=https%3A%2F%2Fhubcloud.foo%2Fdrive%2Fvxaa17iy3ei1aia
OsdFontSize=10
RememberWindowGeometry=true
ShowHeader=false
ShowMenuBar=false

[Playback]
OpenLastPlayedFile=true
RestoreFilePosition=true
YtdlFormat=bestvideo[height<=1440]+bestaudio/best

[Playlist]
OpenWithSingleClick=true
PlaybackBehavior=StopAfterLast
RememberState=true
Style=compact

[Subtitles]
AllowOnBlackBorders=true
FontFamily=SF Pro Display
FontSize=24
PreferredLanguage=eng,hindi

[Video]
DefaultCover=file:///home/nitin/Pictures/patrick-bateman-music-collection.jpg
