[Shortcuts]
Command_0=Ctrl+Shift+R
seekBackwardSmallAction=Alt+H
seekForwardSmallAction=Alt+L
setLoopAction=
subtitleCycleUpAction=
subtitleMoveDownAction=Alt+J
subtitleMoveUpAction=Alt+K
videoPanXLeftAction=H
videoPanXRightAction=L
videoPanYDownAction=J
videoPanYUpAction=K
zoomInAction=E
zoomOutAction=W
zoomResetAction=Shift+R
